### ISSUE TITLE
paper-material accessibility report 

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-material#10]
For the most part, this is all totally fine! Since this is really just the design / visual effect and not meant to be interactive, the screen reader tests don't apply. 

The one piece of feedback I have is that the animations are pretty tough to see, since the gray is so light. Is there anything we can do to make the animation itself a bit more visible?

**Comment by lpalmaro** [comment]
Friendly ping on design ideas here

**Comment by blasten** [comment]
@lpalmaro I recently made the shadows more noticeable in https://github.com/PolymerElements/paper-styles/pull/20.  Therefore, I will close this issue.

**Comment by lpalmaro** [comment]
Awesome - thanks!
