### ISSUE TITLE
Box border and shadow disappears when floated div is inside paper material element

### ISSUE THREAD

**Issue by matas-zanevicius** [PolymerElements/paper-material#16]
My code:

```html
<div class="container">
   <paper-material elevation="3" >
      <div class="col-md-6">
          Content
      </div>
   </paper-material>
</div>
```

.col-md-6 class comes from bootstrap framework, but basically any floated (i.e. in css float:left) div causes the same problem.
I'd appreciate advice on keeping the shadow.

**Comment by notwaldorf** [comment]
What happens if you have this instead?
```
<div class="container">
   <paper-material elevation="3" ></paper-material>
   <div class="col-md-6"> Content</div>
</div>
```

And set the style of the `paper-material` to be absolute fit (`position: absolute`, `top/left/right/bottom: 0`). We've started doing this for `paper-card` and `paper-button` and it worked pretty well.

**Comment by addyosmani** [comment]
@matas-zanevicius Thanks for filing this issue. As it's been quite some time since the last question from @notwaldorf and we didn't hear a response, we're going to close up this ticket. If this is still an issue for you please feel free to reopen and we'll take another look.
