### ISSUE TITLE
paper-material normal padding question

### ISSUE THREAD

**Issue by goof03** [PolymerElements/paper-material#17]
When i use use paper-material in my own element i lost is normal padding. is it normal ? how to restore it please ?

**Comment by notwaldorf** [comment]
Do you have a code snipped or a jsbin of how you're using it in your element?

**Comment by goof03** [comment]
I use it just like that : https://gist.github.com/goof03/3b3cf869040ea846fced
i cant get template repeat working too …

**Comment by lapteuh** [comment]
I have the same issue with padding in paper-material.

**Comment by cdata** [comment]
Thanks for filing an issue. We need to see a reduced test case in order to verify that there is a problem. Please re-open the issue when you have a test case, and consult our [contribution guidelines](../blob/master/CONTRIBUTING.md) for more details on filing issues!
