### ISSUE TITLE
paper-material does not change size with neon-animated-pages

### ISSUE THREAD

**Issue by paranoid-android** [PolymerElements/paper-material#32]
Hello,

I am using some `paper-material` in an app. It looks like this:

```
<paper-material elevation="2">
  <paper-item>
    Welcome  
    <paper-icon-button on-tap="_onView1Tap"></paper-icon-button>
    <paper-icon-button on-tap="_onView2Tap"></paper-icon-button>
  </paper-item>
  
  <neon-animated-pages selected="[[ selectedIndex ]]">
    <neon-animatable>
      <div>This is some content. This content will expand and collapse in size.</div>
    </neon-animatable>

    <neon-animatable>
      <div>
        <div>This is some other content. Please notice that there is also animated content here</div>
        <neon-animated-pages selected="[[ index2 ]]">
          <neon-animatable>
            This is page 1
          </neon-animatable>
          <neon-animatable> 
            This is page 2
          </neon-animatable>
        </neon-animated-pages>
      </div>
    </neon-animatable>
  </neon-animated-pages>
</paper-material>
```

At this time, the `paper-material` does not expand around the `neon-animated-pages` content. I understand that its because the `neon-animated-pages` element has a height of zero. So, I manually set the height at runtime. However, the height of the nested `neon-animated-paged` element is always zero. I can see the content in the view just fine. However, programmatically, it seems to always be zero.

There seems to be a bug in either a) `neon-animated-pages` or b) `paper-material`. Its like `paper-material` was never intended to have animated content within it.

**Comment by jgog** [comment]
I am also experiencing this issue. For me, on window resize the `paper-material` doesn't change size, if I change any style from the Web Inspector it resizes itself.

**Comment by notwaldorf** [comment]
Could you provide a jsbin with the repro steps, please? Here's a template to get you started: http://jsbin.com/kibelo/edit?html,output

**Comment by jgog** [comment]
Really strange but the code works find on jsbin, here http://jsbin.com/mitebawibe/edit?html,output

**Comment by cdata** [comment]
Closing this for now. Please re-open if you can provide a reproducible test case!

**Comment by paranoid-android** [comment]
I updated the sbin to show the issue clearer. As you can see, the `paper-material` does not wrap around the `neon-animated-pages` content.

http://jsbin.com/pabiyuhepi/edit?html,output

**Comment by hyyan** [comment]
This is an old issue , and it is not fixed yet , any ideas ?
