### ISSUE TITLE
mixins in paper-material-shared-styles no longer seem to apply.

### ISSUE THREAD

**Issue by ruifung** [PolymerElements/paper-material#36]
### Description
the mixins from paper-styles/shadow.html no longer seems to be applied.

### Expected outcome
The box shadow is applied.

### Actual outcome
No box shadow is applied.

### Browsers Affected
(Only tested on chromium based browser. Opera)

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

A workaround would be to make the paper-styles/shadow.html into a style module and then include that module in the paper-material-shared-styles.

**Comment by notwaldorf** [comment]
I can't reproduce this: http://jsbin.com/rayeqi/edit?html,output in the latest version. Are your dependencies up to date?
Please re-open if you have a jsbin that can show repro steps.

**Comment by fiws** [comment]
it's only happening with shadom-dom enabled:
http://jsbin.com/jogamisayo/edit?html,output

**Comment by notwaldorf** [comment]
@fiws You are incorrectly setting the `dom` property after polymer has been loaded. You need to do it before, like here: http://jsbin.com/rayeqi/edit?html,output.

Screenshot of that demo, that shows the styles working, and that shadow dom is enabled:
<img width="478" alt="screen shot 2016-05-23 at 10 19 50 am" src="https://cloud.githubusercontent.com/assets/1369170/15478595/104eec72-20d0-11e6-94a7-e27a6a54fad7.png">

**Comment by fiws** [comment]
@notwaldorf ah ok. sorry for the false alarm.
I was trying to reproduce this issue because I am also experiencing it in my app.

I will report back when I can reproduce it in a fiddle.
