### ISSUE TITLE
paper-material crashes depending on the import order

### ISSUE THREAD

**Issue by totegsito** [PolymerElements/paper-material#44]
### Description
If there are any import after paper-material, anything is rendered. However, if it is the last one, everything is ok. It happens in v2.0-preview

### Expected outcome
<img width="480" alt="captura de pantalla 2017-04-04 a las 21 31 02" src="https://cloud.githubusercontent.com/assets/12380342/24675408/57d2d09c-197f-11e7-954f-f3aa30a558f1.png">

### Actual outcome
<img width="617" alt="captura de pantalla 2017-04-04 a las 21 29 55" src="https://cloud.githubusercontent.com/assets/12380342/24675430/67e02d04-197f-11e7-9965-b63cd9f70759.png">

### Steps to reproduce
1. Import paper-material.
2. Import another component.

<img width="529" alt="captura de pantalla 2017-04-04 a las 21 29 39" src="https://cloud.githubusercontent.com/assets/12380342/24675486/9d5c0098-197f-11e7-8545-c77b31e4c5dc.png">
Import code:
https://pastebin.com/zhfw7U2i

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by MWalid** [comment]
👍 I'm getting the same issue with 2.0-preview, however in my case, nothing is showing at all.

**Comment by notwaldorf** [comment]
I strongly recommend _not_ using `paper-material`, and just using the `paper-styles/element-styles/paper-material.html` set of styles (see it's use in [paper-button](https://github.com/PolymerElements/paper-button/blob/2.0-preview/paper-button.html#L114))

**Comment by govis** [comment]
Same issue here. It seems as if distribution through <code>paper-material</code>'s slot breaks under some unknown conditions:

Good:
![image](https://cloud.githubusercontent.com/assets/971651/25533387/808455ba-2bfe-11e7-92c9-204b4526ac27.png)

Bad:
![image](https://cloud.githubusercontent.com/assets/971651/25533433/9cba6da0-2bfe-11e7-85ed-2e417c4df5c0.png)

@notwaldorf your suggestion is helpful, but we still need a generic container element to create ad-hoc card-like layout.

**Comment by dman777** [comment]
I use paper-material element often and have not had any issues for myself. 

I noticed that the paper-material element is not included in the paper-elements collection any longer. If this is intentional, can some kind of documentation or demo be made so new users will know about it and they can use the element in it's new work around?

**Comment by notwaldorf** [comment]
This should be fixed
